server:
  port: 8080

spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      routes:
        - id: meops-cmdb
          uri: http://localhost:9871
          predicates:
            - Path=/meops_cmdb/**
          filters:
            - StripPrefix=1

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always