server:
  port: 8100

spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: false
      routes:
        - id: meops-cmdb
          uri: http://localhost:9871
          predicates:
            - Path=/meops_cmdb/**
          filters:
            - StripPrefix=1
        - id: github
          uri: https://github.com
          predicates:
            - Path=/github/**
          filters:
            - StripPrefix=1

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
